import { Territory, Cache, CacheReward, Resources } from '@/types/game';

// Calculate distance between two coordinates (in meters)
export const calculateDistance = (
  coords1: [number, number],
  coords2: [number, number]
): number => {
  const [lon1, lat1] = coords1;
  const [lon2, lat2] = coords2;
  
  const R = 6371e3; // Earth's radius in meters
  const φ1 = (lat1 * Math.PI) / 180;
  const φ2 = (lat2 * Math.PI) / 180;
  const Δφ = ((lat2 - lat1) * Math.PI) / 180;
  const Δλ = ((lon2 - lon1) * Math.PI) / 180;

  const a =
    Math.sin(Δφ / 2) * Math.sin(Δφ / 2) +
    Math.cos(φ1) * Math.cos(φ2) * Math.sin(Δλ / 2) * Math.sin(Δλ / 2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));

  return R * c;
};

// Check if player is close enough to collect cache (50 meters)
export const canCollectCache = (
  playerLocation: [number, number],
  cacheLocation: [number, number]
): boolean => {
  const distance = calculateDistance(playerLocation, cacheLocation);
  return distance <= 50;
};

// Generate cache rewards based on rarity
export const generateCacheReward = (rarity: Cache['rarity']): CacheReward => {
  const rarityMultiplier = {
    common: 1,
    rare: 2.5,
    epic: 5,
    legendary: 10
  };

  const multiplier = rarityMultiplier[rarity];

  return {
    credits: Math.floor(50 * multiplier),
    materials: Math.floor(20 * multiplier),
    xp: Math.floor(25 * multiplier),
    items: [] // Can add random items later
  };
};

// Calculate resources generated by a territory
export const calculateTerritoryGeneration = (
  territory: Territory,
  hoursElapsed: number
): Resources => {
  const baseRate = 10;
  const levelMultiplier = territory.level;
  const hourlyProduction = baseRate * levelMultiplier;

  return {
    credits: Math.floor(hourlyProduction * hoursElapsed),
    materials: Math.floor((hourlyProduction * 0.5) * hoursElapsed),
    energy: 0
  };
};

// Calculate territory upgrade cost
export const getUpgradeCost = (currentLevel: number): Resources => {
  const baseCost = 100;
  const levelMultiplier = Math.pow(1.5, currentLevel);

  return {
    credits: Math.floor(baseCost * levelMultiplier),
    materials: Math.floor((baseCost * 0.5) * levelMultiplier),
    energy: 0
  };
};

// Check if player can afford upgrade
export const canAffordUpgrade = (
  playerResources: Resources,
  cost: Resources
): boolean => {
  return (
    playerResources.credits >= cost.credits &&
    playerResources.materials >= cost.materials
  );
};

// Calculate time elapsed in hours
export const getHoursElapsed = (lastHarvest: string): number => {
  const now = new Date().getTime();
  const last = new Date(lastHarvest).getTime();
  const millisElapsed = now - last;
  return millisElapsed / (1000 * 60 * 60);
};
